# Copyright 2025 Schelling Point Labs Inc
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "ah-workflows"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
tokio = { version = "1.0", features = ["process", "io-util"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
ah-repo = { path = "../ah-repo" }

[dev-dependencies]
tempfile = "3.0"
tokio = { version = "1.0", features = ["rt", "macros"] }
