[package]
name = "aw-mux"
version = "0.1.0"
edition = "2021"
description = "High-level AW adapter for terminal multiplexers with tmux, kitty, and other backends"
license = "MIT OR Apache-2.0"

[dependencies]
aw-mux-core = { path = "../aw-mux-core" }
thiserror = "1.0"
tokio = { version = "1.0", features = ["process", "io-util"] }
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"

[features]
default = ["tmux"]
tmux = []
kitty = []
wezterm = []
zellij = []
screen = []

[dev-dependencies]
tokio-test = "0.4"
