# Copyright 2025 Schelling Point Labs Inc
# SPDX-License-Identifier: AGPL-3.0-only

# Use node-modules linker for Storybook compatibility
# Storybook 10+ has deprecated PnP support
nodeLinker: node-modules

