include = ["specs/**/*.md"]
exclude = [
  # External blog tends to fail TLS/cert checks intermittently
  "https://www.trio.so/.*",
  # Absolute, site-scoped doc paths used as examples in specs
  "^/en/docs/.*",
  # Volatile or gated docs that frequently 403/redirect or move
  "https://openai.com/blog/openai-codex/.*",
  "https://github.com/OpenAI/openai-codex-cli/.*",
  "https://github.com/google/gemini-cli/.*",
  # Also exclude exact repo URLs without trailing slash
  "https://github.com/OpenAI/openai-codex-cli",
  "https://github.com/google/gemini-cli",
  "https://docs.anthropic.com/.*",
  "https://opencode.dev/.*",
  "https://docs.opencode.dev/.*",
  # Internal file links with spaces (old naming convention - files have been renamed)
  ".*/specs/3rd-Party%20Agents/.*",
  ".*/specs/Multi-OS%20Testing.md",
  ".*/specs/FS%20Snapshots/.*",
  ".*/specs/CLI.md",
  ".*/specs/Agent-Browsers/.*",
  ".*/lib/.*\\.rb",
  ".*/specs/docs/.*",
  ".*/Research/.*",
  # Missing/moved files and directories
  ".*/specs/Public/Agent-Browsers/.*",
  ".*/specs/Public/dynamic-instructions.md",
  ".*/specs/Public/Plans/.*",
  ".*/specs/Public/CLI.status.md",
  ".*/specs/Public/Multi-OS-Testing.md",
  ".*/specs/webui/.*",
  ".*/specs/Sandboxing/.*",
  ".*/specs/TUI-PRD.md",
  # Old URL-encoded file paths
  ".*/3rd-Party%20Agents/.*",
  ".*/FS%20Snapshots/.*",
  ".*/Multi-OS%20Testing.md",
  # Dead external links
  "https://www.5balloons.info/git-commit-template",
  "https://lists.gnu.org/archive/html/help-bash/2025-02/msg00051.html",
  # Rate-limited external sites (429 Too Many Requests) and network issues
  "https://unix.stackexchange.com/.*",
  "https://apple.stackexchange.com/.*",
  "https://medium.com/.*",
  "https://security.stackexchange.com/.*",
  "https://docs.solidjs.com/.*",
  "https://github.com/.*",
  "https://fly.io/.*",
  "https://unikraft.org/.*",
  "https://ignite.readthedocs.io/.*",
  "https://aws.amazon.com/.*",
  "https://www.qemu.org/.*",
  "https://jonathanwoollett-light.github.io/.*",
  "https://www.cloudhypervisor.org/.*",
  "https://igorstechnoclub.com/.*",
  "https://stackoverflow.com/.*",
  "https://www.microsoft.com/.*",
  "https://fruty.medium.com/.*",
  "https://openai.com/codex",
]
max_concurrency = 8
timeout = 20
