# Copyright 2025 Schelling Point Labs Inc
# SPDX-License-Identifier: AGPL-3.0-only

checksumBehavior: ignore

packageExtensions:
  storybook@*:
    peerDependencies:
      storybook-solidjs-vite: '*'
