exclude = [
  "^https://github.com/.*",
  "^https://docs.podman.io/.*",
  "^https://fruty.medium.com/.*",
  "^https://aws.amazon.com/.*",
  "^https://ignite.readthedocs.io/.*",
  "^https://www.qemu.org/.*",
  "^https://wiki.qemu.org/.*",
  "^https://firecracker-microvm.github.io/.*",
  "^https://www.freedesktop.org/.*",
  "^https://docs.kernel.org/.*",
  "^https://arxiv.org/.*",
  "^https://www.cloudhypervisor.org/.*",
  "^https://fly.io/.*",
  "^https://microvm-nix.github.io/.*",
  "^https://unikraft.org/.*",
  "^https://www.paloaltonetworks.com/.*",
  "^https://man7.org/.*",
  "^https://openai.com/.*",
]

# Be lenient with intermittent CDN/SSL issues
max_retries = 2
retry_wait_time = 2
timeout = 20
