exclude = [
  "^https://github.com/.*",
  "^https://docs.podman.io/.*",
  "^https://fruty.medium.com/.*",
  "^https://medium.com/.*",
  "^https://aws.amazon.com/.*",
  "^https://ignite.readthedocs.io/.*",
  "^https://www.qemu.org/.*",
  "^https://wiki.qemu.org/.*",
  "^https://firecracker-microvm.github.io/.*",
  "^https://www.freedesktop.org/.*",
  "^https://www.gnu.org/software/screen/.*",
  "^https://docs.kernel.org/.*",
  "^https://arxiv.org/.*",
  "^https://www.cloudhypervisor.org/.*",
  "^https://fly.io/.*",
  "^https://microvm-nix.github.io/.*",
  "^https://unikraft.org/.*",
  "^https://www.paloaltonetworks.com/.*",
  "^https://man7.org/.*",
  "^https://openai.com/.*",
  "^https://unix.stackexchange.com/.*",
  "^https://stackoverflow.com/.*",
  "^https://opencode.dev/.*",
  "^https://docs.opencode.dev/.*",
  "^https://www.trio.so/.*",
  "/en/docs/.*",
  "^https://www.electronjs.org/.*",
  "^https://lwn.net/.*",
  "^https://news.ycombinator.com/.*",
  "com.apple.WebProcess.sb.in",
]

accept = ["200..=299", "403"]

# Be lenient with intermittent CDN/SSL issues
max_retries = 3
retry_wait_time = 2
timeout = 30
