# Copyright 2025 Schelling Point Labs Inc
# SPDX-License-Identifier: AGPL-3.0-only

# Basic
hard_tabs = false
tab_spaces = 4
max_width = 100

# Consistency
newline_style = "Auto"

# Misc
chain_width = 80

# Modern Style
style_edition = "2024"
