/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Simple "hello world" function to verify N-API integration
 *
 * This function demonstrates that the Rust native addon is correctly
 * loaded and callable from Node.js/Electron.
 *
 * @returns A greeting message from Rust
*/
export declare function helloFromRust(): string
/**
 * Get the current platform
 *
 * @returns The platform name (darwin, linux, win32)
*/
export declare function getPlatform(): string
