[package]
name = "aw-fs-snapshots"
version = "0.1.0"
edition = "2021"
description = "Filesystem snapshot provider abstractions for Agents Workflow"
license = "MIT OR Apache-2.0"

[dependencies]
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
async-trait = "0.1"

[dev-dependencies]
tempfile = "3.8"
regex = "1.10"
libc = "0.2"
aw-repo = { path = "../aw-repo" }

[features]
default = ["zfs", "btrfs", "git"]
zfs = ["dep:aw-fs-snapshots-zfs"]
btrfs = ["dep:aw-fs-snapshots-btrfs"]
git = ["dep:aw-fs-snapshots-git"]

[dependencies.aw-fs-snapshots-btrfs]
path = "../aw-fs-snapshots-btrfs"
optional = true

[dependencies.aw-core]
path = "../aw-core"

[dependencies.aw-fs-snapshots-traits]
path = "../aw-fs-snapshots-traits"

[dependencies.aw-fs-snapshots-zfs]
path = "../aw-fs-snapshots-zfs"
optional = true

[dependencies.aw-fs-snapshots-git]
path = "../aw-fs-snapshots-git"
optional = true
