[package]
name = "tui-exploration"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29"
crossterm = "0.27"
anyhow = "1.0"
chrono = "0.4"
rand = "0.8"
image = { version = "0.25", default-features = false, features = ["png"] }

[dependencies.ratatui-image]
version = "8"
features = ["crossterm"]