[package]
name = "aw-tui-multiplexer"
version = "0.1.0"
edition = "2021"
description = "Agents-Workflow specific multiplexer abstractions for TUI integration"
license = "MIT OR Apache-2.0"

[dependencies]
aw-mux-core = { path = "../aw-mux-core" }
aw-mux = { path = "../aw-mux", default-features = false }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
