[package]
name = "agentfs-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
agentfs-core = { path = "../agentfs-core" }

[dev-dependencies]
tempfile = { workspace = true }
